export const createTestimonialData = [
  {
    key: 0,
    quote:
      'Working with Makerrs has been an excellent experience. Their team was able to effortlessly transform our communication needs into a well crafted campaign. They have been perceptive in understanding our needs as a business, this is what I believe allowed them to come up with creative ideas for the campaign. The team has smoothly executed the plan for us in a short amount of time, with commendable agility for on the fly changes.',
    name: 'KALP PATEL & AYUSH PATEL',
    designation: 'FOUNDERS',
    company: 'L74 CRAFT CIDERS',
    image: {
      srcSet:
        '/img/testimonials/kalp-patel_ayush-patel-1.jpg 533w, /img/testimonials/kalp-patel_ayush-patel-1.jpg 1066w',
      sizes: '(max-width:768px) 533px, 1066px',
    },
  },
  ,
  {
    key: 1,
    quote:
      <>
        <div>
          Makerrs captured the very essence of our brand –the vibrant energy, the quirky charm, and the pure joy of gathering around delicious food. What was especially impressive was the creative strategy that led to the curation of design and copy. They took the colors, the iconic signages, the energy of the local markets, and transformed them into a fresh, modern expression. We&apos;ve seen a tremendous response since the launch. People are drawn to the unique identity. We couldn&apos;t be happier.
        </div>
      </>,
    name: 'KUNCHERIA MARATTUKALAM',
    designation: 'FOUNDER & DIRECTOR',
    company: 'MARATT GROUP',
    image: {
      srcSet:
        '/img/testimonials/kuncheria_marattukalam.jpg',
      sizes: '(max-width:768px) 533px, 1066px',
    },
  },
  {
    key: 2,
    quote:
      'It has been a pleasure to work with the Makerrs team on Project Loom. They are a unique platform that works with a range of directors and cinematographers to produce content across multiple languages and locations. This makes them nimble and effective.',
    name: 'SHOBA NARAYAN',
    designation: 'FOUNDER',
    company: 'PROJECT LOOMS',
    image: {
      srcSet:
        '/img/testimonials/shoba-narayan.webp 533w, /img/testimonials/shoba-narayan.webp 1066w',
      sizes: '(max-width:768px) 533px, 1066px',
    },
  },
  {
    key: 3,
    quote:
      'We worked on 2 films with Makerrs and I can confidently say that the output exceeded our expectations. The team was able to come up with a concept that combined the strong recall of popular culture and at the same time incorporated the brand messaging clearly in the campaign. I would highly recommend them as a reliable and kickass creative partner',
    name: 'BHARAT VIRMANI',
    designation: 'Marketing Manager',
    company: 'Games24x7',
    image: {
      srcSet:
        '/img/testimonials/bharat.webp 533w, /img/testimonials/bharat.webp 1066w',
      sizes: '(max-width:768px) 533px, 1066px',
    },
  }
]

export const scs = {
  logo: {
    src: '/img/dummy/scs/nu-bank.svg',
    width: '260',
    height: '105',
  },
  tags: [
    'Brand Strategy',
    'Voice Branding',
    'DesignDigital',
    'WebContent',
    'Campaigns Events',
    'Activations',
  ],
  featured: {
    src: '/img/dummy/scs/nu-logo.webp',
    width: '1890',
    height: '574',
  },
  problem: {
    title:
      'Neubank, a fast-growing fintech startup, approached Makerrs with the challenge of transforming their digital banking platform. Neubank struggled to deliver a seamless user experience, resulting in low customer satisfaction and retention rates.',
    content: null,
  },
  work: {
    title:
      'Neubank, a leading financial institution, sought to elevate its digital banking experience to meet the evolving needs and expectations of its customers. To achieve this, they partnered with Makerrs, a trusted digital solutions provider, to address their challenges.',
    content: `
      <picture>
        <source
          srcset="/img/dummy/scs/work.webp"
          width="1608"
          height="571"
          media="(min-width:768px)"
        />
        <img
          alt=""
          src="/img/dummy/scs/secondaryimage.webp"
          width="1890"
          height="955"          
          loading="lazy"
        />
      </picture>
      `,
  },
  approach: {
    title:
      'At Makerrs, we believe in the power of creative collaboration to drive impactful results.',
    content:
      'Through a strategic and integrated approach, we worked closely with Nubank to create a range of engaging and visually stunning content pieces. <br/><br/>From concept development to production and post-production, our dedicated team of experts brought their creative prowess and technical expertise to the table.',
    image1: '/img/dummy/scs/image1.webp',
    image2: '/img/dummy/scs/image2.webp',
    secondaryContent: `
    <h3>
      Makerrs&apos;s Innovative Approach for Seamless Customer Onboarding
    </h3>
    <p>
      At Makerrs, we devised an innovative solution to address
      Neubank&apos;s challenges with customer onboarding and engagement. Our
      approach focused on creating a seamless and user-friendly onboarding
      experience for Neubank&apos;s customers. By leveraging cutting-edge
      technologies, user-centric design principles, and personalized
      features, we transformed the onboarding process into a streamlined and
      efficient journey.
    </p>
  `,
    secondaryImage: {
      src: '/img/dummy/scs/secondaryimage.webp',
      width: '1890',
      height: '955',
    },
  },
  steps: {
    content: [
      {
        key: 0,
        title: 'Research and Insight',
        content:
          'We begin by thoroughly understanding your business, target audience, and objectives. Through in-depth research and analysis, we gain valuable insights to shape our strategic approach.',
      },
      {
        key: 1,
        title: 'Brand Strategy',
        content:
          'We begin by thoroughly understanding your business, target audience, and objectives. Through in-depth research and analysis, we gain valuable insights to shape our strategic approach.',
      },
      {
        key: 2,
        title: 'Content Creation and Production',
        content:
          'We begin by thoroughly understanding your business, target audience, and objectives. Through in-depth research and analysis, we gain valuable insights to shape our strategic approach.',
      },
    ],
    image1: '/img/dummy/scs/image1.webp',
    image2: '/img/dummy/scs/image2.webp',
  },
  result: {
    content: `
        <p>
          By leveraging cutting-edge technologies, user-centric design
          principles, and personalized features, we transformed the onboarding
          process into a streamlined and efficient journey.
        </p>
      `,
    points: [
      {
        key: 0,
        stats: {
          title: 'Increase in customer onboarding efficiency',
          value: 30,
          suffix: '%',
        },
      },
      {
        key: 1,
        stats: {
          title: 'Reduction in customer drop-off rate',
          value: 88,
          suffix: '%',
        },
      },
      {
        key: 2,
        stats: {
          title: 'Increase in customer onboarding efficiency',
          value: 22,
          suffix: '+',
        },
      },
      {
        key: 3,
        stats: {
          title: 'Reduction in customer drop-off rate',
          value: 98,
          suffix: '%',
        },
      },
    ],
  },
  press: {
    title: 'Makerrs’s strategic content solutions drive success for Neu',
    image: {
      src: '/img/dummy/scs/press.webp',
      width: '820',
      height: '486',
    },
    content:
      "In a recent collaboration, Makerrs's strategic content solutions proved instrumental in propelling Neubank to new heights. Through meticulous planning and innovative storytelling, Makerrs crafted engaging video content that resonated with Neubank's target audience.",
    href: '#!',
  },
}

export const similarPosts = [
  {
    key: 0,
    name: 'Trip Different',
    company: 'L74 Craft Cider',
    image: '/img/works/l74-strategy.jpg',
    alt: 'metro wholesale ad',
    tags: ['Brand Strategy', 'Campaign Strategy', 'Creative Concepts', 'Content Production', 'Alcobev'],
    href: '/work/l74-case-study',
  }
  // {
  //   key: 0,
  //   name: '5 STAR QUALITY',
  //   company: 'Metro Wholesale',
  //   image: '/img/works/metro-wholesale.jpg',
  //   alt:'metro wholesale ad',
  //   tags: ['Creative Ideation', 'Content Production', 'Content Production'],
  //   href: '/work/create/metro-wholesale-case-study',
  // },
  // {
  //   key: 1,
  //   name: 'Heroes at MyGate',
  //   company: 'MyGate',
  //   image: '/img/works/heros-mygate.jpg',
  //   alt:'heros at mygate ad',
  //   tags: ['Creative Ideation', 'Content Production', 'Content Production'],
  //   href: '/work/create/mygate-case-study',
  // },
  // {
  //   key: 2,
  //   name: 'Swiggy Wali Jacket',
  //   company: 'Swiggy',
  //   image: '/img/works/Swiggy_Wali_Jacket.png',
  //   alt: 'Swiggy Wali Jacket',
  //   tags: ['Creative Ideation', 'Content Production'],
  //   href: '/work/create/swiggy-winter-jacket-case-study',
  // },

]
export const campaignSimilarPosts = [
  {
    key: 0,
    type: 'create',
    name: 'Trip Different',
    company: 'L74 Craft Cider',
    image: '/img/works/l74-strategy.jpg',
    tags: ['Brand Strategy', 'Campaign Strategy', 'Creative Concepts', 'Content Production', 'Alcobev'],
    alt: 'Trip Different with L74 Cider',


    thumbnail: {
      src: '/img/works/l74-placeholder.jpg',
      width: '606',
      height: '874',
    },
    href: '/work/l74-case-study'
  },
  {
    key: 1,
    type: 'create',
    name: 'Indeed for Indian SMBs',
    company: 'Indeed',
    image: '/img/works/indeed_homepage_thumbnail.jpg',
    tags: ['Ad Film', 'Creative Ideation', 'Production'],
    alt: 'Indeed',
    thumbnail: {
      src: '/img/works/indeed_homepage_thumbnail.jpg',
      width: '606',
      height: '874',
    },
    href: '/work/create/indeed-case-study'
  },
  {
    key: 2,
    type: 'create',
    name: '5 STAR QUALITY',
    company: 'Metro Wholesale',
    image: '/img/works/metro-wholesale.jpg',
    alt: 'metro wholesale ad',
    tags: ['Creative Ideation', 'Content Production', 'Content Production'],
    href: '/work/create/metro-wholesale-case-study',
  },

]

export const scsPosts = [
  {
    key: 3,
    name: 'Anniversary Sale',
    company: 'Metro Wholesale',
    image: '/img/dummy/explore-1-lg.webp',
    tags: [
      'Content Strategy',
      'Audience Research and Analysis',
      'Audience Research and Analysis',
    ],
    href: '#!',
  },
  {
    key: 4,
    name: 'Heroes at MyGate',
    company: 'MyGate',
    image: '/img/dummy/explore-2-lg.webp',
    tags: ['Content Strategy', 'Audience Research and Analysis'],
    href: '#!',
  },
  ...similarPosts,
]

export const campaignPosts = [

  {
  key: 0,
  name: 'Transforming how Indian SMBs Hire',
  company: 'Indeed',
  image: '/img/works/indeed.jpg',
  alt: 'Indeed',
  tags: ['Digital Campaign', 'Ad Film', ' Jobs'],
  href: '/brand-campaign/indeed-india-radhika-apte'
},

{
  key: 1,
  name: 'Action-packed campaign film for Redmi Buds 6',
  image: '/img/works/xiaomi_buds_6_work_thumbnail.png',
  company: 'Xiaomi',
  alt: 'Redmi Buds 6',
  tags: [
    'Consumer Electronics',
    'Ad Film',
    'Digital Campaign',
    'Product Launch Campaign'
  ],
  href: '/brand-campaign/xiaomi-buds-6'
},

{
  key: 2,
  name: 'Transforming relationships for SME banks in U.S.A',
  company: 'VYMO',
  alt: 'VYMO',
  image: '/img/works/vymo_sme.webp',
  tags: ['SaaS', 'Digital Campaign', 'Explainer Video', 'Marketing Video'],
  href: '/brand-campaign/vymo-usa-banking',
},
{
    key: 3,
    name: 'Global Leaders: a Hiring Campaign',
    image: '/img/case-study/infosys-global-leaders.webp',
    company: 'Infosys',
    alt: 'infosys-global-leaders',
    tags: [
      'Technology',
      'Campaign',
      'Employer Branding Video',
      'Global Video Production',
    ],
    href: '/brand-campaign/infosys-global-employer-brand',
  },
  {
    key: 4,
    name: 'Branding and Launch Campaign for a Dessert Cafe',
    company: 'P.U. Dingding',
    alt: 'P.U. Dingding',
    tags: [
      'F&B',
      'Brand Visual Identity',
      'Launch Campaign',
      'Social Media Content',
    ],
    image: '/img/works/pdd_intergrated_work_thumbnail.jpg',
    href: '/brand-campaign/pudingding-cafe-design-launch',
  },
  {
    key: 5,
    name: "Campaign films: Season's EXTRA Earnings",
    company: 'Swiggy',
    image: '/img/works/Swiggy_NYE.png',
    alt: 'Swiggy NYE',
    tags: ['Digital Campaign', 'Ad Film', 'Quick Commerce'],
    href: '/brand-campaign/swiggy-extra-earnings',
  },
]

export const contentSolutionPosts = [
  {
    key: 0,
    name: 'Jewels Of India',
    image: '/img/works/jewels_thumbnail.jpg',
    company: 'Taneira',
    alt: 'Jewels Of India',
    tags: ['Short Film', 'Interview', 'Web Series', 'Handcrafted Jewellery', 'Craftsmanship'],
    href: '/work/create/jewels-case-study'
  },
  // {
  //   key: 1,
  //   name: 'Indeed for Indian SMBs',
  //   company: 'Indeed',
  //   image: '/img/works/indeed.jpg',
  //   alt: 'Indeed',
  //   tags: ['Ad Film', 'Creative Ideation', 'Production'],
  //   href: '/work/create/indeed-case-study',
  // },
  {
    key: 2,
    name: 'Heroes at MyGate',
    company: 'MyGate',
    image: '/img/works/heros-mygate.jpg',
    alt: 'heros at mygate ad',
    tags: ['Creative Ideation', 'Content Production', 'Content Production'],
    href: '/work/create/mygate-case-study',
  },
  {
    key: 3,
    name: 'Stories of Indian Weavers and Handlooms',
    company: 'Taneira',
    image: '/img/works/taneira_homepage.jpg',
    alt: 'Taneira',
    tags: ['Short Films', 'Documentaries', 'Web Series', 'Interviews'],
    href: '/work/project-loom',
  },
]

export const contentWorkPosts = [
  {
    key: 0,
    name: 'Jewels Of India',
    image: '/img/works/jewels_thumbnail.jpg',
    company: 'Taneira',
    alt: 'Jewels Of India',
    tags: ['Short Film', 'Interview', 'Web Series', 'Handcrafted Jewellery', 'Craftsmanship'],
    href: '/work/create/jewels-case-study'
  },
  // {
  //   key: 1,
  //   name: 'Indeed for Indian SMBs',
  //   company: 'Indeed',
  //   image: '/img/works/indeed.jpg',
  //   alt: 'Indeed',
  //   tags: ['Ad Film', 'Creative Ideation', 'Production'],
  //   href: '/work/create/indeed-case-study',
  // },
  {
    key: 2,
    name: 'Stories of Indian Weavers and Handlooms',
    company: 'Taneira',
    image: '/img/works/taneira_homepage.jpg',
    alt: 'Taneira',
    tags: ['Short Films', 'Documentaries', 'Web Series', 'Interviews'],
    href: '/work/project-loom',
  },
  {
    key: 3,
    name: 'Heroes at MyGate',
    company: 'MyGate',
    image: '/img/works/heros-mygate.jpg',
    alt: 'heros at mygate ad',
    tags: ['Creative Ideation', 'Content Production', 'Content Production'],
    href: '/work/create/mygate-case-study',
  },
]
export const ccsPosts = [
  {
    key: 0,
    name: 'Trip Different',
    image: '/img/works/l74_strategy_service_work page.jpg',
    company: 'L74 Craft Cider',
    alt: 'Trip Different with L74 Cider',
    tags: ['Brand Strategy', 'Campaign Strategy', 'Creative Concepts', 'Content Production', 'Alcobev'],
    thumbnail: {
      src: '/img/works/l74_strategy_service_work page.jpg',
      width: '606',
      height: '874',
    },
    href: '/work/l74-case-study'
  },
  // {
  //   key: 0,
  //   name: 'Try Ball Offer',
  //   company: ' My 11 Circle',
  //   image: '/img/works/my-11-circle.jpg',
  //   alt:'my 11 circle ',
  //   tags: ['Creative Ideation', 'Content Production', 'Content Production'],
  //   href: '/work/create/my11circle-case-study',
  // },
  // {
  //   key: 1,
  //   name: '5 STAR QUALITY',
  //   company: 'Metro Wholesale',
  //   image: '/img/works/metro-wholesale.jpg',
  //   alt:'metro wholesale ad',
  //   tags: ['Creative Ideation', 'Content Production', 'Content Production'],
  //   href: '/work/create/metro-wholesale-case-study',
  // },
  // {
  //   key: 2,
  //   name: 'Heroes at MyGate',
  //   company: 'MyGate',
  //   image: '/img/works/heros-mygate.jpg',
  //   alt:'heros at mygate ad',
  //   tags: ['Creative Ideation', 'Content Production', 'Content Production'],
  //   href: '/work/create/mygate-case-study',
  // },
  // {
  //   key: 3,
  //   name: 'Swiggy Wali Jacket',
  //   company: 'Swiggy',
  //   image: '/img/works/Swiggy_Wali_Jacket.png',
  //   alt: 'Swiggy Wali Jacket',
  //   tags: ['Creative Ideation', 'Content Production'],
  //   href: '/work/create/swiggy-winter-jacket-case-study',
  // },
  // {
  //   key: 4,
  //   name: 'Swiggy New Year Earning',
  //   company: 'Swiggy',
  //   image: '/img/works/Swiggy_NYE.png',
  //   alt: 'Swiggy NYE',
  //   tags: ['Creative Ideation', 'Content Production'],
  //   href: '/work/create/swiggy-extra-earning-case-study',
  // },
  // {
  //   key: 5,
  //   name: 'Indeed for Indian SMBs',
  //   company: 'Indeed',
  //   image: '/img/works/indeed.jpg',
  //   alt: 'Indeed',
  //   tags: ['Ad Film', 'Creative Ideation', 'Production'],
  //   href: '/work/create/indeed-case-study',
  // },
]

export const ccs = {
  logo: {
    src: '/img/dummy/scs/nu-bank.svg',
    width: '260',
    height: '105',
  },
  tags: [
    'Content Strategy',
    'Audience Research and Analysis',
    'Audience Research and Analysis',
    'Audience Research and Analysis',
  ],
  featured: {
    src: '/img/works/ccs_2x.webp',
    width: '2880',
    height: '1544',
  },
  commercials: {
    title: (
      <>
        Portfolio of video projects that&nbsp;elevated brands and exceeded
        client expectations.
      </>
    ),
    excerpt:
      'Unlock the full potential of your brand with our commercial adaptations. We combine innovative ideas, expert production, and strategic messaging to create captivating commercials that leave a lasting impression.',
    type: 'grid-1',
    sources: {
      image1: {
        src: '/img/dummy/ccs/ccs-1.webp',
        width: '970',
        height: '760',
      },
      image2: {
        src: '/img/dummy/ccs/ccs-2.webp',
        width: '970',
        height: '592',
      },
      image3: {
        src: '/img/dummy/ccs/ccs-3.webp',
        width: '828',
        height: '1423',
      },
      image4: {
        src: '/img/dummy/ccs/ccs-4.webp',
        width: '803',
        height: '1429',
      },
    },
  },
  stats: {
    content: `
    <h3>
    Through our innovative approach, Neubank witnessed significant improvements in customer onboarding and engagement.
    </h3>
    `,
    points: [
      {
        key: 0,
        stats: {
          title: 'increase in customer onboarding in transforming efficiency',
          value: 30,
          suffix: '+',
        },
      },
      {
        key: 1,
        stats: {
          title:
            'reduction in customer drop-off rate during the onboarding process',
          value: 50,
          suffix: '%',
        },
      },
      {
        key: 2,
        stats: {
          title: 'improvement in customer satisfaction and positive feedback',
          value: 80,
          suffix: '%',
        },
      },
    ],
  },
  press: {
    title: 'Makerrs’s strategic content solutions drive success for Neu',
    image: {
      src: '/img/dummy/scs/press.webp',
      width: '820',
      height: '486',
    },
    content:
      "In a recent collaboration, Makerrs's strategic content solutions proved instrumental in propelling Neubank to new heights. Through meticulous planning and innovative storytelling, Makerrs crafted engaging video content that resonated with Neubank's target audience.",
    href: '#!',
  },
}

export const ccs2 = {
  ...ccs,
  commercials: {
    title: (
      <>
        Portfolio of video projects that&nbsp;elevated brands and exceeded
        client expectations.
      </>
    ),
    excerpt:
      'Unlock the full potential of your brand with our commercial adaptations. We combine innovative ideas, expert production, and strategic messaging to create captivating commercials that leave a lasting impression.',
    type: 'video',
    sources: [
      {
        key: 0,
        duration: 15,
        vimeoId: '854986233',
        name: 'GENZ BANKING REVOLUTION',
        company: 'NUEBANK',
        thumbnail: {
          width: 446,
          height: 265,
          src: '/img/dummy/ccs/thumbnail/ccs-t-1.webp',
        },
      },
      {
        key: 1,
        duration: 128,
        vimeoId: '854986233',
        name: 'GENZ BANKING REVOLUTION',
        company: 'NUEBANK',
        thumbnail: {
          width: 446,
          height: 265,
          src: '/img/dummy/ccs/thumbnail/ccs-t-2.webp',
        },
      },
      {
        key: 2,
        duration: 235,
        vimeoId: '854986233',
        name: 'GENZ BANKING REVOLUTION',
        company: 'NUEBANK',
        thumbnail: {
          width: 446,
          height: 265,
          src: '/img/dummy/ccs/thumbnail/ccs-t-3.webp',
        },
      },
      {
        key: 3,
        duration: 355,
        vimeoId: '854986233',
        name: 'GENZ BANKING REVOLUTION',
        company: 'NUEBANK',
        thumbnail: {
          width: 446,
          height: 265,
          src: '/img/dummy/ccs/thumbnail/ccs-t-4.webp',
        },
      },
      {
        key: 4,
        duration: 400,
        vimeoId: '854986233',
        name: 'GENZ BANKING REVOLUTION',
        company: 'NUEBANK',
        thumbnail: {
          width: 446,
          height: 265,
          src: '/img/dummy/ccs/thumbnail/ccs-t-1.webp',
        },
      },
    ],
  },
}
export const ccs3 = {
  ...ccs,
  commercials: {
    title: (
      <>
        Portfolio of video projects that&nbsp;elevated brands and exceeded
        client expectations.
      </>
    ),
    excerpt:
      'Unlock the full potential of your brand with our commercial adaptations. We combine innovative ideas, expert production, and strategic messaging to create captivating commercials that leave a lasting impression.',
    type: 'grid-2',
    sources: {
      image1: {
        src: '/img/dummy/ccs/ccs-8.webp',
        width: '420',
        height: '659',
      },
      image2: {
        src: '/img/dummy/ccs/ccs-7.webp',
        width: '420',
        height: '659',
      },
      image3: {
        src: '/img/dummy/ccs/ccs-6.webp',
        width: '420',
        height: '659',
      },
      image4: {
        src: '/img/dummy/ccs/ccs-5.webp',
        width: '420',
        height: '659',
      },
      image5: {
        src: '/img/dummy/ccs/ccs-5.webp',
        width: '420',
        height: '659',
      },
    },
  },
}
export const ccs4 = {
  ...ccs,
  commercials: {
    title: (
      <>
        Portfolio of video projects that&nbsp;elevated brands and exceeded
        client expectations.
      </>
    ),
    excerpt:
      'Unlock the full potential of your brand with our commercial adaptations. We combine innovative ideas, expert production, and strategic messaging to create captivating commercials that leave a lasting impression.',
    type: 'grid-3',
    sources: {
      image1: {
        src: '/img/dummy/ccs/ccs-11.webp',
        width: '600',
        height: '826',
      },
      image2: {
        src: '/img/dummy/ccs/ccs-9.webp',
        width: '768',
        height: '513',
      },
      image3: {
        src: '/img/dummy/ccs/ccs-12.webp',
        width: '611',
        height: '839',
      },
      image4: {
        src: '/img/dummy/ccs/ccs-10.webp',
        width: '600',
        height: '934',
      },
      image5: {
        src: '/img/dummy/ccs/ccs-13.webp',
        width: '611',
        height: '839',
      },
    },
  },
}

export const ECS_TAG = [
  { key: 0, label: 'Featured Work', value: 'featured' },
  { key: 1, label: 'Explainers', value: 'explainers' },
  { key: 2, label: 'Testimonial', value: 'testimonial' },
  { key: 3, label: 'Animation', value: 'animation' },
  { key: 4, label: 'Product Demo', value: 'product_demo' },
]
export const ecs = [
  {
    key: 0,
    company: 'Belong.co',
    name: 'CEO Series',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-1.webp',
      poster: '/img/dummy/ecs/ecs-1.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'featured',
  },
  {
    key: 1,
    company: 'SWIGGY',
    name: 'Delivery Executive Hiring',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-2.webp',
      poster: '/img/dummy/ecs/ecs-2.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'featured',
  },
  {
    key: 2,
    company: 'Multiplier',
    name: 'Hiring SAAS Explainer',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-3.webp',
      poster: '/img/dummy/ecs/ecs-3.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'featured',
  },
  {
    key: 3,
    company: 'Goibibo',
    name: 'Hiring Video',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-4.webp',
      poster: '/img/dummy/ecs/ecs-4.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'featured',
  },
  {
    key: 4,
    company: 'TRELL',
    name: 'New Packaging Launch',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-5.webp',
      poster: '/img/dummy/ecs/ecs-5.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'featured',
  },
  {
    key: 5,
    company: 'Hansel',
    name: 'Product Explainer',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-6.webp',
      poster: '/img/dummy/ecs/ecs-6.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'featured',
  },
  {
    key: 6,
    company: 'IKEA',
    name: 'Product Showcase',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-7.webp',
      poster: '/img/dummy/ecs/ecs-7.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'featured',
  },
  {
    key: 7,
    company: 'WIPRO',
    name: 'Wipro Australia Brand Film',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-8.webp',
      poster: '/img/dummy/ecs/ecs-8.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'featured',
  },
  {
    key: 8,
    company: 'Belong.co',
    name: 'CEO Series',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-1.webp',
      poster: '/img/dummy/ecs/ecs-1.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'featured',
  },
  {
    key: 9,
    company: 'SWIGGY',
    name: 'Delivery Executive Hiring',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-2.webp',
      poster: '/img/dummy/ecs/ecs-2.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'featured',
  },
  {
    key: 10,
    company: 'Multiplier',
    name: 'Hiring SAAS Explainer',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-1.webp',
      poster: '/img/dummy/ecs/ecs-1.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'explainers',
  },
  {
    key: 11,
    company: 'Goibibo',
    name: 'Hiring Video',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-2.webp',
      poster: '/img/dummy/ecs/ecs-2.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'explainers',
  },
  {
    key: 12,
    company: 'TRELL',
    name: 'New Packaging Launch',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-1.webp',
      poster: '/img/dummy/ecs/ecs-1.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'testimonial',
  },
  {
    key: 13,
    company: 'Hansel',
    name: 'Product Explainer',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-2.webp',
      poster: '/img/dummy/ecs/ecs-2.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'testimonial',
  },
  {
    key: 14,
    company: 'IKEA',
    name: 'Product Showcase',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-1.webp',
      poster: '/img/dummy/ecs/ecs-1.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'animation',
  },
  {
    key: 15,
    company: 'WIPRO',
    name: 'Wipro Australia Brand Film',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-2.webp',
      poster: '/img/dummy/ecs/ecs-2.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'animation',
  },
  {
    key: 16,
    company: 'Belong.co',
    name: 'CEO Series',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-2.webp',
      poster: '/img/dummy/ecs/ecs-2.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'product_demo',
  },
  {
    key: 17,
    company: 'SWIGGY',
    name: 'Delivery Executive Hiring',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-1.webp',
      poster: '/img/dummy/ecs/ecs-1.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'featured',
  },
  {
    key: 18,
    company: 'Multiplier',
    name: 'Hiring SAAS Explainer',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-2.webp',
      poster: '/img/dummy/ecs/ecs-2.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'featured',
  },
  {
    key: 19,
    company: 'Goibibo',
    name: 'Hiring Video',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-3.webp',
      poster: '/img/dummy/ecs/ecs-3.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'featured',
  },
  {
    key: 20,
    company: 'TRELL',
    name: 'New Packaging Launch',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-4.webp',
      poster: '/img/dummy/ecs/ecs-4.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'featured',
  },
  {
    key: 21,
    company: 'Hansel',
    name: 'Product Explainer',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-5.webp',
      poster: '/img/dummy/ecs/ecs-5.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'featured',
  },
  {
    key: 22,
    company: 'IKEA',
    name: 'Product Showcase',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-6.webp',
      poster: '/img/dummy/ecs/ecs-6.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'featured',
  },
  {
    key: 23,
    company: 'WIPRO',
    name: 'Wipro Australia Brand Film',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-7.webp',
      poster: '/img/dummy/ecs/ecs-7.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'featured',
  },
  {
    key: 24,
    company: 'Belong.co',
    name: 'CEO Series',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-8.webp',
      poster: '/img/dummy/ecs/ecs-8.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'featured',
  },
  {
    key: 25,
    company: 'SWIGGY',
    name: 'Delivery Executive Hiring',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-1.webp',
      poster: '/img/dummy/ecs/ecs-1.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'featured',
  },
  {
    key: 26,
    company: 'Multiplier',
    name: 'Hiring SAAS Explainer',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-2.webp',
      poster: '/img/dummy/ecs/ecs-2.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'featured',
  },
  {
    key: 27,
    company: 'Goibibo',
    name: 'Hiring Video',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-1.webp',
      poster: '/img/dummy/ecs/ecs-1.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'explainers',
  },
  {
    key: 28,
    company: 'TRELL',
    name: 'New Packaging Launch',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-2.webp',
      poster: '/img/dummy/ecs/ecs-2.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'explainers',
  },
  {
    key: 29,
    company: 'Hansel',
    name: 'Product Explainer',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-1.webp',
      poster: '/img/dummy/ecs/ecs-1.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'testimonial',
  },
  {
    key: 30,
    company: 'IKEA',
    name: 'Product Showcase',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-2.webp',
      poster: '/img/dummy/ecs/ecs-2.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'testimonial',
  },
  {
    key: 31,
    company: 'WIPRO',
    name: 'Wipro Australia Brand Film',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-1.webp',
      poster: '/img/dummy/ecs/ecs-1.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'animation',
  },
  {
    key: 32,
    company: 'Belong.co',
    name: 'CEO Series',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-2.webp',
      poster: '/img/dummy/ecs/ecs-2.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'animation',
  },
  {
    key: 33,
    company: 'SWIGGY',
    name: 'Delivery Executive Hiring',
    content:
      'Discover seamless account management, intuitive budgeting tools, secure transactions, and personalized financial insights, all at your fingertips. Watch the video now and unlock a world of financial possibilities with Neubank.',
    video: {
      src: '/img/dummy/ecs/ecs-2.webp',
      poster: '/img/dummy/ecs/ecs-2.webp',
      width: 3840,
      height: 2160,
    },
    width: 3840,
    height: 2160,
    ratio: '16:9',
    duration: '30:08',
    fps: 30,
    type: 'product_demo',
  },
]

export const strategyPosts = [
  {
    key: 0,
    name: 'Launching an AI-powered healthcare brand in record time',
    company: 'Lillia Care',
    image: '/img/works/lillia_img.jpg',
    alt: 'Lillia Care',
    tags: ['Healthtech', 'Brand Identity', 'Website Design', 'Website Development'],
    href: '/brand-designs/lillia-care-brand-launch'
  },

  {
    key: 1,
    name: "Exicom Brand Refresh: Choose Smart. Charge Smart.",
    company: 'Exicom',
    image: '/img/case-study/exicom_brand_refresh_work.jpg',
    alt: 'Exicom',
    tags: ['E-Mobility', 'Design', 'Brand Transformation', 'Visual Identity'],
    href: '/brand-designs/exicom-EV-charger-rebrand',
  },


  {
    key: 2,
    name: 'Branding for an Indulgent Dessert Café',
    company: 'P.U. Dingding',
    image: '/img/works/pudingding-thumbnail.jpg',
    tags: ['F&B', 'Cafe', 'Brand Identity', 'Launch Video'],
    href: '/brand-designs/pu-dingding-cafe',
  },
  {
    key: 3,
    name: 'Crafting a Symbol of Success in Hospitality',
    company: 'Medalio',
    image: '/img/case-study/medalio_thumbnail.webp',
    tags: ['Hospitality', 'Brand Identity', 'Logo Design'],
    href: '/brand-designs/medalio-hotel-brand-identity',
  },
  {
    key: 4,
    name: 'Branding for a Desi Street Food Restaurant',
    company: 'Thelagram',
    image: '/img/works/thelagram.jpg',
    tags: [
      'Brand Visual Identity',
      'Pacakaging Design',
      'Logo Design',
      'Wall Branding',
      'Digital Campaign',
      'F&B',
    ],
    href: '/brand-design/thelagram-restaurant',
  },
  {
    key: 5,
    name: 'Augmented Reality that brought the automobile alive',
    company: 'Bajaj Auto',
    image: '/img/works/bajaj_pulsar_work_age.webp',
    tags: ['Automotive', 'XR Solution (AR/VR/MR)', 'Gamified Experience'],
    href: '/brand-design/bajaj-pulsar-augmented-reality',
  },
]

 export const videoPosts = [
    {
    key: 0,
    name: 'Global Leaders: a Hiring Campaign',
    image: '/img/case-study/infosys-global-leaders.webp',
    company: 'Infosys',
    alt: 'infosys-global-leaders',
    tags: ['Technology', 'Campaign', 'Employer Branding Video', 'Global Video Production'],
    href: '/brand-campaign/infosys-global-employer-brand',
  },
  {
    key: 1,
    name: '220% Organic YouTube Subscriber Growth in India',
    company: 'Indeed',
    alt: 'Indeed YouTube Content',
    tags: ['Hiring Platform', 'YouTube Content'],
    image: '/img/works/indeed_youtube_content_main_thumbnail.png',
    href: '/video-production/indeed-youtube-content',
  },
  {
    key: 2,
    name: 'Campaign Explainer Video for HRM SAAS product',
    company: 'MULTIPLIER',
    image: '/img/works/multiplier_work.webp',
    alt: 'MULTIPLIER',
    tags: ['SaaS', 'Lead Gen Campaign', 'Product Launch Video', 'Explainer Video', '2D Animation Video'],
    href: '/video-production/multiplier-explainer-video',
  },
  {
      key: 3,
      name: 'Gordon Ritter on the Future of Software',
      company: 'Vymo',
      image: '/img/works/vymo_gordon_ritter.webp',
      alt: 'Vymo',
      tags: [
        'SaaS',
        'Thought Leadership Video',
        'Corporate Film',
        'Interview Video',
      ],
      href: '/video-production/thought-leadership-vymo-gordon-ritter',
    },
    {
      key: 4,
      name: 'Capturing the Story of Sanganeri Craft for Taneira',
      company: 'Taneira',
      alt: 'Sanganeri Craft with Taneira',
      tags: ['Textile and Apparel', 'Documentary Film'],
      image: '/img/works/taneira_main_thumbnail.png',
      href: '/video-production/fashion-taneira-sanganeri',
    },
    {
      key: 31,
      name: "Celebrating Rural Women in India's Auto Manufacturing",
      company: 'Tata Motors',
      alt: " Celebrating Rural Women in India's Auto Manufacturing",
      tags: [
        'Manufacturing',
        'Employer Branding',
        'Corporate Communication',
        'Diversity & Inclusion',
      ],
      image: '/img/works/womens-at-tata-autocamp.webp',
      href: '/video-production/tata-inclusion-auto-comp',
    },
]

export const featuredPlay = ecs.slice(0, 8)

export const workPosts = [
  {
    key: 96,
    name: 'Transforming how Indian SMBs Hire',
    company: 'Indeed',
    image: '/img/works/indeed.jpg',
    alt: 'Indeed',
    tags: ['Digital Campaign', 'Ad Film', ' Jobs'],
    tabs: ['Featured'],
    filter_type : ['b2b','b2c'],
    case_study_title: 'indeed-india-radhika-apte',
    href: '/brand-campaign/indeed-india-radhika-apte',
    region: ['IN'], // only visible for India
  },
  {
    key: 97,
    name: '220% Organic YouTube Subscriber Growth in India',
    company: 'Indeed',
    alt: 'Indeed YouTube Content',
    tags: ['Hiring Platform', 'YouTube Content'],
    tabs: ['Featured'],
    filter_type : ['b2c'],
    image: '/img/works/indeed_youtube_content_main_thumbnail.png',
    case_study_title: 'indeed-youtube-content',
    href: '/video-production/indeed-youtube-content',
    region: ['IN'], // only visible for India
  },
  {
    key: 0,
    name: 'Global Leaders: a Hiring Campaign',
    image: '/img/case-study/infosys-global-leaders.webp',
    company: 'Infosys',
    alt: 'infosys-global-leaders',
    tabs: ['Featured'],
    filter_type : ['b2b'],
    tags: [
      'Technology',
      'Campaign',
      'Employer Branding Video',
      'Global Video Production',
    ],
    case_study_title: 'infosys-global-employer-brand',
    href: '/brand-campaign/infosys-global-employer-brand',
    region: [],
  },
  {
    key: 1,
    name: 'Action-packed launch film for Redmi Buds 6',
    image: '/img/works/xiaomi_buds_6_work_thumbnail.png',
    company: 'Xiaomi',
    alt: 'Redmi Buds 6',
    tabs: ['Featured'],
    filter_type : ['b2c'],
    tags: [
      'Consumer Electronics',
      'Ad Film',
      'Digital Campaign',
      'Product Launch Campaign',
    ],
    case_study_title: 'xiaomi-buds',
    href: '/brand-campaign/xiaomi-buds',
    region: [],
  },
  {
    key: 98,
    name: 'Never sweat the first game Campaign Films',
    company: ' My 11 Circle',
    image: '/img/works/my-11-circle.jpg',
    alt: 'my 11 circle ',
    tags: ['Digital Campaign', 'Ad Film', 'Fantasy Games'],
    tabs: ['Featured'],
    filter_type : ['b2c'],
    case_study_title: 'my11circle-case-study',
    href: '/brand-campaign/my11circle-digital-ad-film',
    region: ['IN'], // only visible for India
  },
  {
    key: 99,
    name: "Campaign: When you can't resist buying more",
    company: 'Metro Wholesale',
    alt: 'Swiggy',
    tags: ['Retail', 'TV Campaign', 'Ad Film'],
    tabs: ['Featured'],
    filter_type : ['b2c'],
    image: '/img/works/metro-wholesale-one-minute.webp',
    case_study_title: 'metro-wholesale-one-minute',
    href: '/brand-campaign/metro-wholesale-one-more',
    region: ['IN'],
  },
  {
    key: 2,
    name: 'Launching an AI-powered healthcare brand in record time',
    company: 'Lillia Care',
    image: '/img/works/lillia_img.jpg',
    alt: 'Lillia Care',
    tags: [
      'Healthtech',
      'Brand Identity',
      'Website Design',
      'Website Development',
    ],
    tabs: ['Featured'],
    filter_type : ['b2b'],
    case_study_title: 'lillia-care-brand-launch',
    href: '/brand-designs/lillia-care-brand-launch',
    region: [],
  },
  {
    key: 3,
    name: 'Branding and Launch Campaign for a Dessert Cafe',
    company: 'P.U. Dingding',
    alt: 'P.U. Dingding',
    tags: [
      'F&B',
      'Brand Visual Identity',
      'Launch Campaign',
      'Social Media Content',
    ],
    tabs: ['Featured'],
    filter_type : ['b2c'],
    image: '/img/works/pdd_intergrated_work_thumbnail.jpg',
    case_study_title: 'pdd-integrated',
    href: '/brand-campaign/pudingding-cafe-design-launch',
    region: [],
  },

  {
    key: 4,
    name: 'Powering education in war-torn Ukraine, with Street Child',
    company: 'Infosys',
    image: '/img/works/infosys_springboard.webp',
    alt: 'Infosys',
    filter_type : ['b2b'],
    tags: ['Technology', 'Non-profit', 'CSR Video', 'Corporate Film'],
    tabs: ['Featured'],
    case_study_title: 'csr-video-infosys-street-child',
    href: '/video-production/csr-video-infosys-street-child',
    region: [],
  },
  {
    key: 5,
    name: 'Sales Digitisation Campaign - Interactive Explainer',
    image: '/img/works/slb_work.webp',
    company: 'SLB',
    alt: 'slb',
    tabs: ['Featured'],
    filter_type : ['b2b'],
    tags: [
      'Engineering',
      'Campaign',
      'Explainer Video',
      'Demo Video',
      'Interactive Video',
    ],
    case_study_title: 'interactive-explainer-slb',
    href: '/brand-campaign/interactive-explainer-slb',
    region: [],
  },
  {
    key: 6,
    name: 'Exicom Brand Refresh: Choose Smart. Charge Smart.',
    company: 'Exicom',
    image: '/img/case-study/exicom_brand_refresh_work.jpg',
    tags: ['E-Mobility', 'Design', 'Brand Transformation', 'Visual Identity'],
    tabs: ['Featured'],
    filter_type : ['b2b','b2c'],
    case_study_title: 'exicom-EV-charger-rebrand',
    href: '/brand-designs/exicom-EV-charger-rebrand',
    region: [],
  },

  {
    key: 7,
    name: 'Gordon Ritter on the Future of Software',
    company: 'Vymo',
    image: '/img/works/vymo_gordon_ritter.webp',
    alt: 'Vymo',
    tags: [
      'SaaS',
      'Thought Leadership Video',
      'Corporate Film',
      'Interview Video',
    ],
    tabs: ['Featured'],
     filter_type : ['b2b'],
    case_study_title: 'vymo-gordon-ritter-thought-leadership-video',
    href: '/video-production/thought-leadership-vymo-gordon-ritter',
    region: [],
  },

  {
    key: 8,
    name: 'Augmented Reality that brought the automobile alive',
    image: '/img/works/bajaj_pulsar_work_age.webp',
    company: 'Bajaj Auto',
    alt: 'Augmented Reality that brought the automobile alive',
    tabs: ['Featured'],
    filter_type : ['b2b'],
    tags: ['Automotive', 'XR Solution (AR/VR/MR)', 'Gamified Experience'],
    case_study_title: 'bajaj-pulsar-augmented-reality',
    href: '/brand-design/bajaj-pulsar-augmented-reality',
    region: [],
  },

  {
    key: 9,
    name: 'Immersive 3D Walkthrough for Infosys Topaz',
    image: '/img/works/infosys-thobaz.webp',
    company: 'Infosys',
    alt: 'Immersive 3D Walkthrough for Infosys Topaz',
    tabs: ['Featured'],
    filter_type : ['b2b'],
    tags: [
      'Technology',
      'Interactive Experience',
      '3D Animation Video',
      'Marketing Video',
    ],
    case_study_title: 'infosys-topaz-3d-interactive-experience',
    href: '/brand-design/3d-interactive-experience-infosys-topaz',
    region: [],
  },

  {
    key: 10,
    name: 'Transforming relationships for SME banks in U.S.A',
    company: 'VYMO',
    image: '/img/works/vymo_sme.webp',
    tags: ['SaaS', 'Digital Campaign', 'Explainer Video', 'Marketing Video'],
    tabs: ['Featured'],
    filter_type : ['b2b'],
    case_study_title: 'vymo-sme-bank-explainer-video',
    href: '/brand-campaign/vymo-usa-banking',
    region: [],
  },

  {
    key: 11,
    name: 'Crafting a Unified Employer Brand Across Continents',
    company: 'Infosys',
    image: '/img/works/infosys_eb_campaign_work_thumbnail.png',
    alt: 'Infosys',
    tags: [
      'Technology',
      'Employer Branding Campaign',
      'Global Video Production',
      'Interview Video',
    ],
    tabs: ['Featured'],
    filter_type : ['b2b'],
    case_study_title: 'infosys-employer-branding',
    href: '/video-production/global-employer-branding',
    region: [],
  },

  {
    key: 12,
    name: 'Explainer Video for HRM SAAS product',
    company: 'MULTIPLIER',
    image: '/img/works/multiplier_work.webp',
    tags: [
      'SaaS',
      'Lead Gen Campaign',
      'Product Launch Video',
      'Explainer Video',
      '2D Animation Video',
    ],
    tabs: ['Featured'],
     filter_type : ['b2b'],
    case_study_title: 'multiplier-hr-saas-explainer-video',
    href: '/video-production/multiplier-explainer-video',
    region: [],
  },

  {
    key: 13,
    name: 'AI-Powered Campaign That Inspires Employees To Imagine Their Best Selves',
    image: '/img/case-study/infosys_thrive_main_new.jpg',
    // company: 'Infosys',
    alt: 'AI-Powered Campaign - Employees Imagine their Best Selves',
    tabs: ['Featured'],
    tags: [
      'Technology',
      'AI',
      'Digital Campaign',
      'Hyper-Personalized Campaign',
    ],
     filter_type : ['b2b'],
    case_study_title: 'infosys-thrive-ai-powered-campaign',
    href: '/brand-campaign/employee-wellbeing-ai-experience',
    region: [],
  },

  // Design starts

  {
    key: 14,
    name: 'Launching an AI-powered healthcare brand in record time',
    company: 'Lillia Care',
    image: '/img/works/lillia_img.jpg',
    alt: 'Lillia Care',
    tags: [
      'Healthtech',
      'Brand Identity',
      'Website Design',
      'Website Development',
    ],
    tabs: ['design'],
    case_study_title: 'lillia-care-brand-launch',
    href: '/brand-designs/lillia-care-brand-launch',
    region: [],
  },

  {
    key: 15,
    name: 'Exicom Brand Refresh: Choose Smart. Charge Smart.',
    company: 'Exicom',
    image: '/img/case-study/exicom_brand_refresh_work.jpg',
    tags: ['E-Mobility', 'Design', 'Brand Transformation', 'Visual Identity'],
    tabs: ['design'],
    case_study_title: 'exicom-EV-charger-rebrand',
    href: '/brand-designs/exicom-EV-charger-rebrand',
    region: [],
  },

  {
    key: 16,
    name: 'Branding for an Indulgent Dessert Café',
    company: 'P.U. Dingding',
    image: '/img/case-study/pudingding-thumbnail.jpg',
    tags: ['F&B', 'Cafe', 'Brand Identity', 'Launch Video'],
    tabs: ['design'],
    case_study_title: 'pu-dingding-cafe',
    href: '/brand-designs/pu-dingding-cafe',
    region: [],
  },

  {
    key: 17,
    name: 'Crafting a Symbol of Success in Hospitality',
    image: '/img/case-study/medalio_thumbnail.webp',
    company: 'Medalio',
    alt: 'Medalio',
    tabs: ['design'],
    tags: ['Hospitality', 'Brand Identity', 'Logo Design'],
    case_study_title: 'medalio-hotel-brand-identity',
    href: '/brand-designs/medalio-hotel-brand-identity',
    region: [],
  },

  {
    key: 18,
    name: 'Branding for a Desi Street Food Restaurant',
    image: '/img/works/thelagram.jpg',
    company: 'Thelagram',
    alt: 'Thelagram',
    tabs: ['design'],
    tags: [
      'Brand Visual Identity',
      'Pacakaging Design',
      'Logo Design',
      'Wall Branding',
      'Digital Campaign',
      'F&B',
    ],
    case_study_title: 'thelagram',
    href: '/brand-design/thelagram-restaurant',
    region: [],
  },

  {
    key: 19,
    name: 'Augmented Reality that brought the automobile alive',
    image: '/img/works/bajaj_pulsar_work_age.webp',
    company: 'Bajaj Auto',
    alt: 'Augmented Reality that brought the automobile alive',
    tabs: ['design'],
    tags: ['Automotive', 'XR Solution (AR/VR/MR)', 'Gamified Experience'],
    case_study_title: 'bajaj-pulsar-augmented-reality',
    href: '/brand-design/bajaj-pulsar-augmented-reality',
    region: [],
  },

  {
    key: 20,
    name: 'Immersive 3D Walkthrough for Infosys Topaz',
    image: '/img/works/infosys-thobaz.webp',
    company: 'Infosys',
    alt: 'Immersive 3D Walkthrough for Infosys Topaz',
    tabs: ['design'],
    tags: [
      'Technology',
      'Interactive Experience',
      '3D Animation Video',
      'Marketing Video',
    ],
    case_study_title: 'infosys-topaz-3d-interactive-experience',
    href: '/brand-design/infosys-topaz-3d-interactive-experience',
    region: [],
  },

  {
    key: 21,
    name: 'Nationwide Activation Celebrating Customer Obsession',
    company: 'Axis Bank',
    image: '/img/case-study/axis_bank_work_thumbnail.jpg',
    tags: ['Finance', 'Internal Communications Campaign', 'Marketing Campaign'],
    tabs: ['design'],
    case_study_title: 'axis-bank-activation-campaign',
    href: '/brand-design/axis-bank-activation-campaign',
    region: [],
  },

  {
    key: 22,
    name: 'Social Media Campaign: Meet the AI-First Employees',
    company: 'Infosys',
    image: '/img/works/infy-ai-first-work.webp',
    tags: [
      'Technology',
      'Digital Campaign',
      'Employer Branding video',
      'Social Media Content',
    ],
    tabs: ['design'],
    case_study_title: 'animated-case-study-videos-infosys-employees',
    href: '/brand-campaign/animated-case-study-videos-infosys-employees',
    region: [],
  },

  {
    key: 23,
    name: 'Launching a Sports Brand logo with a 3D Billboard',
    image: '/img/works/mumbai-indians.webp',
    company: 'Mumbai Indians',
    alt: 'Launching a Sports Brand logo with a 3D Billboard',
    tabs: ['design'],
    tags: ['Sports', '3D Billboard Animation'],
    case_study_title: '3d-logo-animation-mumbai-indians',
    href: '/video-production/3d-logo-animation-mumbai-indians',
    region: [],
  },
  {
    key: 24,
    name: 'A Design Gallery on Sustainability',
    image: '/img/works/infosys-living-labs-gallery.jpg',
    company: 'Infosys',
    alt: 'infosys-living-labs-gallery',
    tabs: ['design'],
    tags: [
      'Technology',
      'Integrated Design Services',
      'Brand Experience',
      'ESG',
    ],
    case_study_title: 'infosys-sustainability-gallery',
    href: '/brand-design/infosys-sustainability-gallery',
    region: [],
  },

  {
    key: 25,
    name: "Office Branding for Biocon's Global Headquarters",
    company: 'Biocon',
    image: '/img/case-study/biocon_work_thumbnail.png',
    tags: [
      'Biopharmaceutical',
      'Integrated Design Services',
      'Brand Experience',
    ],
    tabs: ['design'],
    case_study_title: 'biocon-office-branding',
    href: '/brand-design/biocon-office-branding',
    region: [],
  },

  // Videos starts

  {
    key: 26,
    name: 'Global Leaders: a Hiring Campaign',
    image: '/img/case-study/infosys-global-leaders.webp',
    company: 'Infosys',
    alt: 'infosys-global-leaders',
    tabs: ['videos'],
     filter_type : ['b2b'],
    tags: [
      'Technology',
      'Campaign',
      'Employer Branding Video',
      'Global Video Production',
    ],
    case_study_title: 'infosys-global-leaders-employer-branding',
    href: '/brand-campaign/infosys-global-employer-brand',
    region: [],
  },
  {
    key: 27,
    name: '220% Organic YouTube Subscriber Growth in India',
    company: 'Indeed',
    alt: 'Indeed YouTube Content',
    tags: ['Hiring Platform', 'YouTube Content'],
    tabs: ['videos'],
    image: '/img/works/indeed_youtube_content_main_thumbnail.png',
    case_study_title: 'indeed-youtube-content',
    href: '/video-production/indeed-youtube-content',
    region: ['IN'],
    filter_type : ['b2c'],
  },
  {
    key: 28,
    name: 'Campaign Explainer Video for HRM SAAS product',
    company: 'MULTIPLIER',
    image: '/img/works/multiplier_work.webp',
    filter_type : ['b2b'],
    tags: [
      'SaaS',
      'Lead Gen Campaign',
      'Product Launch Video',
      'Explainer Video',
      '2D Animation Video',
    ],
    tabs: ['videos'],
    case_study_title: 'multiplier-hr-saas-explainer-video',
    href: '/video-production/multiplier-explainer-video',
    region: [],
  },
  {
    key: 29,
    name: 'Gordon Ritter on the Future of Software',
    company: 'Vymo',
    image: '/img/works/vymo_gordon_ritter.webp',
    alt: 'Vymo',
    filter_type : ['b2b'],
    tags: [
      'SaaS',
      'Thought Leadership Video',
      'Corporate Film',
      'Interview Video',
    ],
    tabs: ['videos'],
    case_study_title: 'vymo-gordon-ritter-thought-leadership-video',
    href: '/video-production/thought-leadership-vymo-gordon-ritter',
    region: [],
  },
  {
    key: 30,
    name: 'Capturing the Story of Sanganeri Craft for Taneira',
    company: 'Taneira',
    alt: 'Sanganeri Craft with Taneira',
    tags: ['Textile and Apparel', 'Documentary Film'],
    tabs: ['videos'],
    image: '/img/works/taneira_main_thumbnail.png',
    case_study_title: 'taneira-sanganeri',
    href: '/video-production/fashion-taneira-sanganeri',
    region: [],
    filter_type : ['b2c'],
  },
  {
    key: 31,
    name: "Celebrating Rural Women in India's Auto Manufacturing",
    company: 'Tata Motors',
    alt: " Celebrating Rural Women in India's Auto Manufacturing",
    tags: [
      'Manufacturing',
      'Employer Branding',
      'Corporate Communication',
      'Diversity & Inclusion',
    ],
    tabs: ['videos'],
    image: '/img/works/womens-at-tata-autocamp.webp',
    case_study_title: 'women-in-auto-manufacturing',
    href: '/video-production/tata-inclusion-auto-comp',
    region: ['IN'],
    filter_type : ['b2c'],
  },
  {
    key: 32,
    name: 'Unveiling Harmony Direct 2.0 - Electric Fleet Charger',
    company: 'Exicom',
    image: '/img/works/exicom_work_thumbnail.png',
    alt: 'Exicom',
    tags: [
      'Mobility',
      'Product Launch Video',
      'Marketing Video',
      '3D Animation Video',
    ],
    filter_type : ['b2b'],
    tabs: ['videos'],
    case_study_title: '3d-product-reveal-video-exicom',
    href: '/video-production/3d-product-reveal-video-exicom',
    region: [],
  },
  {
    key: 33,
    name: 'Global Case Study Videos for Infosys',
    company: 'Infosys',
    image: '/img/works/wsj-thumbnail.png',
    alt: 'Infosys',
    filter_type : ['b2b'],
    tags: [
      'Technology',
      'Case Study Video',
      'Testimonial Video',
      'Global Video Production',
    ],
    tabs: ['videos'],
    case_study_title: 'infosys-wsj-global-case-study-video',
    href: '/video-production/case-study-videos-infosys-wsj',
    region: [],
  },
  {
    key: 34,
    name: 'HIRING STEM EDUCATORS FOR INDONESIA',
    company: 'COLEARN',
    image: '/img/works/stem-educators-wanted.png',
    tags: [
      'Ed-tech',
      'Employer Branding & Recruitment Campaign',
      'Hiring Video',
    ],
    tabs: ['videos'],
    filter_type : ['b2b'],
    case_study_title: 'colearn-stem-educators-recruitment-video',
    href: '/video-production/recruitment-video-colearn-education',
    region: [],
  },
  {
    key: 35,
    name: 'Powering education in war-torn Ukraine, with Street Child',
    company: 'Infosys',
    image: '/img/works/infosys_springboard.webp',
    alt: 'Infosys',
    tags: ['Technology', 'Non-profit', 'CSR Video', 'Corporate Film'],
    tabs: ['videos'],
    filter_type : ['b2b'],
    case_study_title: 'csr-video-infosys-street-child',
    href: '/video-production/csr-video-infosys-street-child',
    region: [],
  },
  {
    key: 36,
    name: 'Social Media Campaign: Meet the AI-First Employees',
    company: 'Infosys',
    image: '/img/works/infy-ai-first-work.webp',
    tags: [
      'Technology',
      'Digital Campaign',
      'Employer Branding video',
      'Social Media Content',
    ],
    tabs: ['videos'],
    filter_type : ['b2b'],
    case_study_title: 'animated-case-study-videos-infosys-employees',
    href: '/brand-campaign/animated-case-study-videos-infosys-employees',
    region: [],
  },
  {
    key: 37,
    name: 'Launching a Sports Brand logo with a 3D Billboard',
    image: '/img/works/mumbai-indians.webp',
    company: 'Mumbai Indians',
    filter_type : ['b2c'],
    alt: 'Launching a Sports Brand logo with a 3D Billboard',
    tabs: ['videos'],
    tags: ['Sports', '3D Billboard Animation'],
    case_study_title: '3d-logo-animation-mumbai-indians',
    href: '/video-production/3d-logo-animation-mumbai-indians',
    region: [],
  },
  {
    key: 38,
    name: 'A GenAI Microdrama for Bharat',
    image: '/img/works/class-room-poster.jpg',
    company: 'Makerrs',
    alt: 'Makerrs',
    filter_type : ['b2c'],
    tabs: ['videos'],
    tags: ['Gen AI Videos', 'Short-form Content', 'Digital Storytelling'],
    case_study_title: 'shaanu-ka-viva',
    href: '/video-production/microdrama-shaanu-ka-viva',
    region: ['IN'],
  },
  {
    key: 39,
    name: 'An ode to the Security Personnel who Guard our Homes',
    company: 'MyGate',
    image: '/img/works/heros-mygate.jpg',
    alt: 'heros at mygate ad',
    tags: ['Digital Campaign', 'Video Content', 'B2C SAAS'],
    tabs: ['videos'],
    case_study_title: 'mygate-case-study',
    href: '/video-production/poetic-video-mygate',
    region: ['IN'],
    filter_type : ['b2c'],
  },
  {
    key: 40,
    name: 'A Campaign film for Xiaomi Pocket Power Bank',
    company: 'Xiaomi',
    alt: 'A Campaign film for Xiaomi Pocket Power Bank',
    tags: [
      'Consumer Electronics',
      'Ad Film',
      'Digital Campaign',
      'Product Launch Campaign',
    ],
    tabs: ['videos'],
    image: '/img/works/xiaomi-thumnail.webp',
    case_study_title: 'xiaomi-pocket-power-bank',
    href: '/video-production/3d-product-video-xiaomi-mini-power-bank',
    region: [],
    filter_type : ['b2c'],
  },
  {
    key: 41,
    name: 'Launching the Cobalt Cloud Community',
    company: 'Infosys',
    alt: 'Cobalt Community Launch',
    tabs: ['videos'],
    filter_type : ['b2b'],
    image: '/img/works/cobalt_community.jpg',
    tags: [
      'Technology',
      'Digital Campaign',
      'Platform Launch Video',
      '2D Animation Video',
    ],
    case_study_title: 'infosys-cobalt-community-launch-video',
    href: '/video-production/abstract-animation-video-infosys-cobalt-launch',
    region: [],
  },
  {
    key: 42,
    name: '#HeroesAtMyGate: Celebrating India’s Security Guards',
    company: 'Mygate',
    alt: 'Mygate Rewards and Recognition',
    tags: ['B2C SaaS', 'Digital Campaign', 'Video Content'],
    tabs: ['videos'],
    filter_type : ['b2c'],
    image: '/img/works/mygate_rewards_Thumbnail.png',
    case_study_title: 'mygate-rewards-recognition',
    href: '/video-production/mygate-rewards-recognition',
    region: ['IN'],
  },
  {
    key: 43,
    name: "Celebrating Wipro's journey and growth in Australia",
    company: 'Wipro',
    image: '/img/works/wipro_img.webp',
    alt: 'Wipro',
    filter_type : ['b2b'],
    tags: ['Technology', 'Corporate Film', 'Corporate Communication Campaign'],
    tabs: ['videos'],
    case_study_title: 'wipro-australia-corporate-film',
    href: '/video-production/wipro-australia-corporate-film',
    region: [],
  },
  {
    key: 44,
    name: 'Gen AI Ad for Single-Origin Coffee Range',
    image: '/img/works/swiggy_insanely_good_video_thumbnail.png',
    company: 'Swiggy',
    alt: 'Swiggy',
    filter_type : ['b2c'],
    tabs: ['videos'],
    tags: ['Quick Commerce', 'Gen AI Video', 'Ad Film'],
    case_study_title: 'ai-video-swiggy',
    href: '/video-production/ai-video-swiggy',
    region: [],
  },
  {
    key: 45,
    name: "High-energy rap music video on Tata Women's Cricket Premiere League",
    image: '/img/works/tata-women cricket-filmwork-thumbnail.webp',
    company: 'Tata Motors',
    alt: 'tata-women cricket-filmwork-thumbnail',
    tabs: ['videos'],
    tags: ['Video Content', 'Employer Branding', 'Sports League', 'Featured'],
    case_study_title: 'tata-womens-cricket-league',
    href: '/video-production/rap-video-tata-womens-cricket-league',
    region: [],
    filter_type : ['b2c'],
  },
  {
    key: 46,
    name: 'Anywhere chat support for Delivery Executives',
    company: 'Swiggy',
    alt: 'Swiggy',
    tags: ['Quick Commerce', 'Product Demo Video', 'Internal Communication'],
    tabs: ['videos'],
    image: '/img/works/swiggy-thumbnail.webp',
    case_study_title: 'app-walkthrough-swiggy-delivery',
    href: '/brand-campaign/app-walkthrough-swiggy-delivery',
    region: ['IN'],
    filter_type : ['b2c'],
  },
  {
    key: 47,
    name: 'How Hansel Helps Brands Boost Conversions',
    image: '/img/case-study/hansel_work_page_thumbnail.png',
    company: 'Hansel',
    alt: 'How Hansel Helps Brands Boost Conversions',
    tabs: ['videos'],
    tags: [
      'SaaS',
      'Explainer Video',
      'Marketing Video',
      'Product Launch Video',
    ],
    case_study_title: 'hansel-saas-explainer-video',
    href: '/video-production/saas-explainer-video-hansel',
    region: [],
    filter_type : ['b2b'],
  },
  {
    key: 48,
    name: 'Sales Digitisation Campaign - Interactive Explainer',
    image: '/img/works/slb_work.webp',
    company: 'SLB',
    alt: 'slb',
    tabs: ['videos'],
    tags: [
      'Engineering',
      'Campaign',
      'Explainer Video',
      'Demo Video',
      'Interactive Video',
    ],
    case_study_title: 'interactive-explainer-slb',
    href: '/brand-campaign/interactive-explainer-slb',
    region: [],
    filter_type : ['b2b'],
  },
  {
    key: 49,
    name: 'IT Consulting firm delivers Business Agility Solution',
    company: 'Infosys',
    image: '/img/works/infosys_business_agility_work_thumbnail.png',
    alt: 'Infosys',
    tags: ['Technology', 'Marketing Video'],
    tabs: ['videos'],
    filter_type : ['b2b'],
    case_study_title: 'infosys-business-agility-solution',
    href: '/video-production/stock-footage-video-infosys-business-agility',
    region: [],
  },
  {
    key: 50,
    name: 'Corporate Film for Aerospace Manufacturing giant in India',
    company: 'GE Aerospace',
    image: '/img/works/ge_aerospace.webp',
    alt: 'GE Aerospace',
    filter_type : ['b2b'],
    tags: ['Manufacturing', 'Aerospace', 'Corporate Films & Videos'],
    tabs: ['videos'],
    case_study_title: 'ge-aerospace-corporate-film',
    href: '/video-production/ge-aerospace-corporate-film',
    region: [],
  },
  {
    key: 51,
    name: 'Documentaries: Traditional Indian Handlooms and Weavers',
    company: 'Taneira',
    image: '/img/works/taneira_homepage.jpg',
    alt: 'Taneira',
    tags: ['Digital Campaign', 'Video Content', 'Textile &  Apparel'],
    tabs: ['videos'],
    case_study_title: 'project-loom',
    href: '/video-production/documentary-taneira-fashion',
    region: [],
    filter_type : ['b2c'],
  },
  {
    key: 52,
    name: 'Hiring for "Hotel Superhero", hospitality SAAS',
    company: 'Treebo Hotels',
    image: '/img/works/treebo_img.webp',
    alt: 'Treebo Hotels',
    tags: [
      'Hospitality Tech',
      'Hiring Video',
      'Employer Branding',
      'Testimonial Video',
    ],
    tabs: ['videos'],
    case_study_title: 'hotel-superhero-saas-hiring-video',
    href: '/video-production/hiring-video-hotel-superhero',
    region: [],
    filter_type : ['b2b'],
  },
  {
    key: 53,
    name: 'How a Healthtech Startup Gamified Workplace Wellness',
    image: '/img/case-study/healthify_work_thumbnail.png',
    company: 'HealthifyMe App',
    alt: 'How a Healthtech Startup Gamified Workplace Wellness',
    tabs: ['videos'],
    filter_type : ['b2b'],
    tags: [
      'Health & Fitness',
      'Marketing Campaign',
      'Product Launch Video',
      'Testimonial and Case Study Videos',
    ],
    case_study_title: 'healthifyme-employee-wellness-app-video',
    href: '/video-production/employee-wellness-healthifyme-app-video',
    region: [],
  },
  {
    key: 54,
    name: ' Documentaries: Indian Handcrafted Jewellery and Craftspeople ',
    image: '/img/works/jewels_thumbnail.jpg',
    company: 'Taneira',
    filter_type : ['b2c'],
    alt: 'Jewels Of India',
    tags: ['Digital Campaign', 'Video Content', 'Jewellery'],
    tabs: ['videos'],
    case_study_title: 'documentary-tanishq-jewels',
    href: '/video-production/documentary-tanishq-jewels',
    region: [],
  },
  {
    key: 55,
    name: 'HEALTHTECH AND INSURTECH CASE STUDY VIDEOS FOR HIMSS',
    company: 'WIPRO',
    image: '/img/works/casestudy-for-himss.webp',
    tags: [
      'Healthtech',
      'Case Study Video',
      'Explainer Video',
      '2D Animation Video',
    ],
    tabs: ['videos'],
    case_study_title: 'wipro-healthtech-case-study-videos',
    href: '/video-production/healthcare-case-study-video-wipro',
    region: [],
    filter_type : ['b2b'],
  },
  {
    key: 56,
    name: "Highlighting the impact of Dozee Beds in India's Healthcare",
    image: '/img/works/dozee-work.webp',
    company: 'Dozee',
    alt: 'dozee',
    tabs: ['videos'],
    tags: ['MedTech', 'PR Video', 'Video Report'],
    case_study_title: 'dozee-beds-healthcare-video-report',
    href: '/video-production/video-report-dozee-public-health',
    region: [],
    filter_type : ['b2b'],
  },
  {
    key: 57,
    name: 'Immersive 3D Walkthrough for Infosys Topaz',
    image: '/img/works/infosys-thobaz.webp',
    company: 'Infosys',
    alt: 'Immersive 3D Walkthrough for Infosys Topaz',
    tabs: ['videos'],
    tags: [
      'Technology',
      'Interactive Experience',
      '3D Animation Video',
      'Marketing Video',
    ],
    case_study_title: 'infosys-topaz-3d-interactive-experience',
    href: '/brand-design/3d-interactive-experience-infosys-topaz',
    region: [],
    filter_type : ['b2b'],
  },
  {
    key: 58,
    name: 'Koo Launches Self-Verification',
    image: '/img/case-study/koo_work_thumbnail.png',
    company: 'Koo',
    alt: 'Koo',
    filter_type : ['b2b'],
    tabs: ['videos'],
    tags: ['Social Network', 'Explainer Video', '2D Animation Video'],
    case_study_title: 'koo-self-verification-explainer-video',
    href: '/video-production/explainer-video-koo',
    region: [],
  },
  {
    key: 59,
    name: 'A hiring video with humor and heart',
    company: 'Darwinbox',
    image: '/img/works/darwinbox_main_thumbnail.png',
    alt: 'Darwinbox',
    filter_type : ['b2b'],
    tags: ['HR Tech', 'Hiring Video', 'Employer Branding', 'Culture Video'],
    tabs: ['videos'],
    case_study_title: 'darwinbox-hiring-video',
    href: '/video-production/hiring-video-darwinbox',
    region: [],
  },
  {
    key: 60,
    name: 'Launching the Cyanotype clothing range',
    image: '/img/works/taneira-cyanotype main-thumbnail.webp',
    company: 'Taneira',
    alt: 'Launching the Cyanotype clothing range',
    tags: ['Textile and Apparel', ' Documentary Film'],
    tabs: ['videos'],
    case_study_title: 'taneira-cyanotype',
    href: '/video-production/fashion-taneira-cyanotype',
    region: [],
    filter_type : ['b2c'],
  },
  {
    key: 61,
    name: 'Transforming relationships for SME banks in U.S.A',
    company: 'VYMO',
    image: '/img/works/vymo_sme.webp',
    tags: ['SaaS', 'Digital Campaign', 'Explainer Video', 'Marketing Video'],
    tabs: ['videos'],
    case_study_title: 'explainer-video-vymo-USA-banking',
    href: '/brand-campaign/explainer-video-vymo-USA-banking',
    region: [],
    filter_type : ['b2b'],
  },
  {
    key: 62,
    name: 'Stories of Innovation & Impact at Texas instruments India',
    company: 'Texas Instruments',
    image: '/img/works/ti_main_work_thumbnail.png',
    alt: 'Texas Instruments',
    tags: [
      'Semiconductor Manufacturing',
      'Employer Branding',
      'Corporate Commuication',
      'Culture Video',
    ],
    tabs: ['videos'],
    case_study_title: 'people-first-brand-films-for-ti',
    href: '/video-production/culture-videos-texas-instruments',
    region: [],
    filter_type : ['b2b'],
  },
  {
    key: 63,
    name: 'Inspiring Campus Recruitment Video',
    company: 'Infosys',
    image: '/img/works/life_infosys_work_thumbnail.png',
    alt: 'Infosys',
    tags: [
      'Technology',
      'Hiring Video',
      'Employer Branding Video`',
      'Culture Video',
    ],
    tabs: ['videos'],
    case_study_title: 'infosys-campus-recruitment-video',
    href: '/video-production/recruitment-video-infosys-campus',
    region: [],
    filter_type : ['b2b'],
  },
  {
    key: 64,
    name: 'Supporting young women in pursuit of a Future in STEM',
    company: 'WeRise',
    image: '/img/works/we_rise.webp',
    alt: 'WeRise',
    filter_type : ['b2b'],
    tags: ['Non-profit', 'CSR Video', 'Documentary'],
    tabs: ['videos'],
    case_study_title: 'women-in-STEM-documentary',
    href: '/video-production/women-in-STEM-documentary',
    region: [],
  },
  {
    key: 65,
    name: 'The Lakshmi Rebecca Show: YouTube Series on Impact Businesses',
    image: '/img/works/lrs.png',
    company: 'Lakshmi Rebecca',
    alt: 'The Lakshmi Rebecca Show',
    tabs: ['videos'],
    filter_type : ['b2c'],
    tags: ['Video Content', 'YouTube Series'],
    case_study_title: 'lakshmi-rebecca-show',
    href: '/video-podcast/podcast-lakshmi-rebecca',
    region: [],
  },
  {
    key: 66,
    name: 'Crafting a Unified Employer Brand Across Continents',
    company: 'Infosys',
    image: '/img/works/infosys_eb_campaign_work_thumbnail.png',
    alt: 'Infosys',
    tags: [
      'Technology',
      'Employer Branding Campaign',
      'Global Video Production',
      'Interview Video',
    ],
    filter_type : ['b2b'],
    tabs: ['videos'],
    case_study_title: 'infosys-employer-branding',
    href: '/video-production/employer-branding-videos-infosys',
    region: [],
  },
  {
    key: 67,
    name: 'Launching a brand that makes commerce human',
    image: '/img/case-study/infy-equinox.webp',
    company: 'Infosys Equinox',
    alt: 'infy-equinox',
    filter_type : ['b2b'],
    tabs: ['videos'],
    tags: [
      'SaaS',
      'Marketing Campaign',
      'Brand Launch',
      'Video',
      'Thought Leadership',
    ],
    case_study_title: 'infosys-equinox-brand-launch',
    href: '/brand-campaign/launch-infosys-equinox',
    region: [],
  },
  {
    key: 68,
    name: 'A Vision for Sustainable Social Housing',
    company: 'WeRise',
    image: '/img/works/werise.png',
    alt: 'WeRise',
    tags: ['Non-profit', 'Documentary'],
    tabs: ['videos'],
    case_study_title: 'werise-sustainable-housing-documentary',
    href: '/video-production/sustainable-housing-documentary',
    region: [],
    filter_type : ['b2b'],
  },
  {
    key: 69,
    name: 'Building Pathways for Skilled Plumbers',
    company: 'Ashirvad',
    image: '/img/case-study/shirvad_pipes.png',
    alt: 'Ashirvad',
    tags: ['Manufacturing', 'CSR Video'],
    tabs: ['videos'],
    case_study_title: 'ashirvad-plumbing-school-csr-video',
    href: '/video-production/csr-video-ashirvad',
    region: [],
    filter_type : ['b2b'],
  },

  // Campaign starts

  {
    key: 70,
    name: 'Transforming how Indian SMBs Hire',
    company: 'Indeed',
    image: '/img/works/indeed.jpg',
    alt: 'Indeed',
    tags: ['Digital Campaign', 'Ad Film', ' Jobs'],
    tabs: ['campaign'],
    case_study_title: 'indeed-india-radhika-apte',
    href: '/brand-campaign/indeed-india-radhika-apte',
    region: ['IN'],
    filter_type : ['b2c','b2b'],
  },

  {
    key: 71,
    name: 'Action-packed campaign film for Redmi Buds 6',
    image: '/img/works/xiaomi_buds_6_work_thumbnail.png',
    company: 'Xiaomi',
    alt: 'Redmi Buds 6',
    tabs: ['campaign'],
    tags: [
      'Consumer Electronics',
      'Ad Film',
      'Digital Campaign',
      'Product Launch Campaign',
    ],
    case_study_title: 'xiaomi-buds',
    href: '/brand-campaign/xiaomi-buds-6',
    region: [],
    filter_type : ['b2c'],
  },

  {
    key: 72,
    name: 'Transforming relationships for SME banks in U.S.A',
    company: 'VYMO',
    image: '/img/works/vymo_sme.webp',
    tags: ['SaaS', 'Digital Campaign', 'Explainer Video', 'Marketing Video'],
    tabs: ['campaign'],
    case_study_title: 'vymo-sme-bank-explainer-video',
    href: '/brand-campaign/vymo-usa-banking',
    region: [],
    filter_type : ['b2b'],
  },

  {
    key: 73,
    name: 'Global Leaders: a Hiring Campaign',
    image: '/img/case-study/infosys-global-leaders.webp',
    company: 'Infosys',
    alt: 'infosys-global-leaders',
    tabs: ['campaign'],
    tags: [
      'Technology',
      'Campaign',
      'Employer Branding Video',
      'Global Video Production',
    ],
    filter_type : ['b2b'],
    case_study_title: 'infosys-global-leaders-employer-branding',
    href: '/brand-campaign/infosys-global-employer-brand',
    region: [],
  },

  {
    key: 74,
    name: 'Branding and Launch Campaign for a Dessert Cafe',
    company: 'P.U. Dingding',
    alt: 'P.U. Dingding',
    tags: [
      'F&B',
      'Brand Visual Identity',
      'Launch Campaign',
      'Social Media Content',
    ],
    tabs: ['campaign'],
    image: '/img/works/pdd_intergrated_work_thumbnail.jpg',
    case_study_title: 'pdd-integrated',
    href: '/brand-campaign/pudingding-cafe-design-launch',
    region: [],
    filter_type : ['b2c'],
  },

  {
    key: 75,
    name: "Campaign films: Season's EXTRA Earnings",
    company: 'Swiggy',
    image: '/img/works/Swiggy_NYE.png',
    alt: 'Swiggy NYE',
    tags: ['Digital Campaign', 'Ad Film', 'Quick Commerce'],
    tabs: ['campaign'],
    case_study_title: 'swiggy-extra-earning-case-study',
    href: '/brand-campaign/swiggy-extra-earnings',
    region: ['IN'],
    filter_type : ['b2c'],
  },

  {
    key: 76,
    name: 'Launching a brand that makes commerce human',
    image: '/img/case-study/infy-equinox.webp',
    company: 'Infosys Equinox',
    alt: 'infy-equinox',
    tabs: ['campaign'],
    tags: [
      'SaaS',
      'Marketing Campaign',
      'Brand Launch',
      'Video',
      'Thought Leadership',
    ],
    case_study_title: 'infosys-equinox-brand-launch',
    href: '/brand-campaign/infosys-equinox-launch',
    region: [],
    filter_type : ['b2b'],
  },

  {
    key: 77,
    name: 'Launch Campaign for Redmi A4 5G',
    company: 'Xiaomi',
    image: '/img/works/xiaomi-a4-5g.png',
    alt: 'Launch Campaign for Redmi A4 5G',
    tabs: ['campaign'],
    tags: [
      'Consumer Electronics',
      'Ad Film',
      'Digital Campaign',
      'Product Launch Campaign',
    ],
    case_study_title: 'xiaomi-a4-5g',
    href: '/brand-campaign/xiaomi-a4-5g-phone',
    region: ['IN'],
    filter_type : ['b2c'],
  },

  {
    key: 78,
    name: 'Campaign film for Door Step Gold Loans',
    image: '/img/works/indiagold_thumbanail.webp',
    company: 'IndiaGold',
    alt: 'IndiaGold',
    tabs: ['campaign'],
    tags: ['Digital Campaign', 'Ad Film', 'Fintech'],
    case_study_title: 'indiagold',
    href: '/brand-campaign/indiagold',
    region: ['IN'],
    filter_type : ['b2c'],
  },

  {
    key: 79,
    name: 'Crafting a Unified Employer Brand Across Continents',
    company: 'Infosys',
    image: '/img/works/infosys_eb_campaign_work_thumbnail.png',
    alt: 'Infosys',
    tabs: ['campaign'],
    tags: [
      'Technology',
      'Employer Branding Campaign',
      'Global Video Production',
      'Interview Video',
    ],
    case_study_title: 'infosys-employer-branding',
    href: '/video-production/global-employer-branding',
    region: [],
    filter_type : ['b2b'],
  },

  {
    key: 80,
    name: 'Trip Different with L74 Ciders',
    company: 'L74 Craft Cider',
    alt: 'Trip Different with L74 Cider',
    tags: [
      'Brand Strategy',
      'Brand Postioning',
      'Brand Launch Strategy',
      'Digital Campaign',
      'Social Media Content',
      'Alcobev',
    ],
    filter_type : ['b2c'],
    tabs: ['campaign'],
    image: '/img/works/l74_strategy_service_work page.jpg',
    case_study_title: 'l74-case-study',
    href: '/brand-campaign/l74-ciders-social-media',
    region: [],
  },

  {
    key: 81,
    name: 'Never sweat the first game Campaign Films',
    company: ' My 11 Circle',
    image: '/img/works/my-11-circle.jpg',
    alt: 'my 11 circle ',
    tags: ['Digital Campaign', 'Ad Film', 'Fantasy Games'],
    tabs: ['campaign'],
    case_study_title: 'my11circle-case-study',
    href: '/brand-campaign/my11circle-digital-ad-film',
    region: ['IN'],
    filter_type : ['b2c'],
  },

  {
    key: 82,
    name: 'Social Media Campaign: Meet the AI-First Employees',
    company: 'Infosys',
    image: '/img/works/infy-ai-first-work.webp',
    tags: [
      'Technology',
      'Digital Campaign',
      'Employer Branding video',
      'Social Media Content',
    ],
    filter_type : ['b2b'],
    tabs: ['campaign'],
    case_study_title: 'animated-case-study-videos-Infosys-employees',
    href: '/brand-campaign/animated-case-study-videos',
    region: [],
  },

  {
    key: 83,
    name: 'A Trimmer Launch Campaign that’s as Sharp as the Product',
    company: 'Xiaomi',
    alt: 'A Trimmer Launch Campaign that’s as Sharp as the Product',
    tags: [
      'Consumer Electronics',
      'Ad Film',
      'Digital Campaign',
      'Product Launch Campaign',
    ],
    tabs: ['campaign'],
    image: '/img/works/xiaomi-bread-trimmer.webp',
    case_study_title: 'xiaomi-beard-trimmer',
    href: '/brand-campaign/xiaomi-beard-trimmer',
    region: [],
    filter_type : ['b2c'],
  },

  {
    key: 84,
    name: 'Digital Campaign videos for E-learning courses',
    company: 'Jigsaw',
    image: '/img/works/jigsaw_work.webp',
    tags: [
      'Ed-tech',
      'Digital Campaign',
      'Marketing Video',
      'Product Launch Video',
    ],
    tabs: ['campaign'],
    case_study_title: 'jigsaw-e-learning-explainer-video',
    href: '/brand-campaign/unext-course-marketing',
    region: [],
    filter_type : ['b2b'],
  },

  {
    key: 85,
    name: 'AI-Powered Campaign That Inspires Employees To Imagine Their Best Selves',
    image: '/img/case-study/infosys_thrive_main_new.jpg',
    alt: 'AI-Powered Campaign - Employees Imagine their Best Selves',
    tabs: ['campaign'],
    tags: [
      'Technology',
      'AI',
      'Digital Campaign',
      'Hyper-Personalized Campaign',
    ],
    case_study_title: 'infosys-thrive-ai-powered-campaign',
    href: '/brand-campaign/employee-wellbeing-ai-experience',
    region: [],
    filter_type : ['b2b'],
  },

  {
    key: 86,
    name: 'Launch Campaign for Redmi Buds 5C',
    image: '/img/works/xiaomi_buds_5c_main_thumbnail.webp',
    company: 'XIAOMI',
    alt: 'Xiaomi Redmi Buds 5C',
    tabs: ['campaign'],
    filter_type : ['b2c'],
    tags: [
      'Consumer Electronics',
      'Ad Film',
      'Digital Campaign',
      'Product Launch Campaign',
    ],
    case_study_title: 'xiaomi-buds-5c',
    href: '/brand-campaign/xiaomi-buds-5c',
    region: [],
  },

  {
    key: 87,
    name: 'Augmented Reality that brought the automobile alive',
    image: '/img/works/bajaj_pulsar_work_age.webp',
    company: 'Bajaj Auto',
    alt: 'Augmented Reality that brought the automobile alive',
    tabs: ['campaign'],
    tags: ['Automotive', 'XR Solution (AR/VR/MR)', 'Gamified Experience'],
    case_study_title: 'bajaj-pulsar-augmented-reality',
    href: '/brand-design/bajaj-pulsar-augmented-reality',
    region: [],
    filter_type : ['b2b'],
  },

  {
    key: 88,
    name: 'Campaign on Inclusive Lingerie',
    image: '/img/works/zivame_work.webp',
    company: 'Zivame',
    alt: 'Campaign on Inclusive Lingerie',
    tags: ['Digital Campaign', 'Product Video', 'Video Content', 'E-commerce'],
    tabs: ['campaign'],
    href: '/brand-campaign/zivame-lingerie',
    region: [],
    filter_type : ['b2c'],
  },

  {
    key: 89,
    name: '5 Star Quality at Wholesale Prices',
    company: 'Metro Wholesale',
    image: '/img/works/metro-wholesale.jpg',
    alt: 'metro wholesale ad',
    tags: ['Retail', 'TV Campaign', 'Ad Film'],
    tabs: ['campaign'],
    case_study_title: 'metro-wholesale-case-study',
    href: '/brand-campaign/metro-wholesale-5-star-quality',
    region: ['IN'],
    filter_type : ['b2c','b2b'],
  },

  {
    key: 90,
    name: 'A Lead Management Product for Financial Services',
    image: '/img/case-study/vymo-lead-management.webp',
    company: 'Vymo',
    alt: 'vymo-lead-management ',
    tabs: ['campaign'],
    tags: ['SaaS', 'Digital Campaign', 'Explainer Video', 'Marketing Video'],
    case_study_title: 'vymo-lead-management',
    href: '/brand-campaign/vymo-lead-management',
    region: [],
    filter_type : ['b2b'],
  },

  {
    key: 91,
    name: 'A Campaign film for Xiaomi Pocket Power Bank',
    company: 'Xiaomi',
    alt: 'A Campaign film for Xiaomi Pocket Power Bank',
    tags: [
      'Consumer Electronics',
      'Ad Film',
      'Digital Campaign',
      'Product Launch Campaign',
    ],
    tabs: ['campaign'],
    image: '/img/works/xiaomi-thumnail.webp',
    case_study_title: 'xiaomi-pocket-power-bank',
    href: '/video-production/xiaomi-pocket-power-bank',
    region: [],
    filter_type : ['b2c'],
  },

  {
    key: 92,
    name: 'AI-powered Singalong Campaign that united a Global Workforce',
    image: '/img/case-study/singalong.jpg',
    alt: 'AI-powered Singalong Campaign that united a Global Workforce',
    tabs: ['campaign'],
    filter_type : ['b2b'],
    tags: [
      'Technology',
      'AI',
      'Digital Campaign',
      'Hyper-Personalized Campaign',
      'Global Video Production',
    ],
    case_study_title: 'infosys-ai-powered-singalong-campaign',
    href: '/brand-campaign/ai-powered-singalong',
    region: [],
  },

  {
    key: 93,
    name: "Campaign: When you can't resist buying more",
    company: 'Metro Wholesale',
    alt: 'Swiggy',
    tags: ['Retail', 'TV Campaign', 'Ad Film'],
    tabs: ['campaign'],
    image: '/img/works/metro-wholesale-one-minute.webp',
    case_study_title: 'metro-wholesale-one-minute',
    href: '/brand-campaign/metro-wholesale-one-more',
    region: ['IN'],
    filter_type : ['b2c','b2b'],
  },

  {
    key: 94,
    name: 'Campaign films: Winter Jackets',
    company: 'Swiggy',
    image: '/img/works/Swiggy_Wali_Jacket.png',
    alt: 'Campaign films: Winter Jackets',
    tags: ['Digital Campaign', 'Ad Film', 'Quick Commerce'],
    tabs: ['campaign'],
    href: '/brand-campaign/swiggy-winter-jackets',
    region: ['IN'],
    filter_type : ['b2c'],
  },

  {
    key: 95,
    name: 'Transforming Field Sales for Insurance Wholesalers in USA',
    image: '/img/case-study/vymo-wholesale.webp',
    company: 'Vymo',
    alt: 'vymo-wholesalers',
    tabs: ['campaign'],
    tags: ['SaaS', 'Digital Campaign', 'Explainer Video', 'Marketing Video'],
    case_study_title: 'vymo-wholesalers-explainer-video',
    href: '/brand-campaign/vymo-insurance-wholesale',
    region: [],
    filter_type : ['b2b'],
  },
]

export const explorecards = [
    {
      id: 0,
      serviceTitle: 'GET DESIGN',
      serviceDescription:
        'Get brand identity systems, event branding, editorial design, illustrations, and motion graphics. Build brand differentiation and human connect with Makerrs. Explore our branding and design services.',
      bgColor: '#ffffff',
      textColor: '#13c33f',
      href: '/brand-design-agency',
    },
    {
      id: 1,
      serviceTitle: 'GET VIDEO',
      serviceDescription:
        'We plan, conceptualise, produce and scale video content – be it for your next product or your YouTube channel. We also offer on-demand video production services for customer testimonial videos, recruitment videos, corporate videos and more. Explore our video production services.',
      bgColor: '#ffffff',
      textColor: '#13c33f',
      href: '/video-production',
    },
    {
      id: 2,
      serviceTitle: 'GET PODCAST',
      serviceDescription:
        'Looking to lead industry conversations, build community and drive ROI? Go from content research, podcast concept and positioning, to podcast branding, production, distribution and amplification with one agency. Make a successful podcast today.',
      bgColor: '#ffffff',
      textColor: '#13c33f',
      href: '/podcast-production-services',
    },
    {
      id: 3,
      serviceTitle: 'GET CAMPAIGN',
      serviceDescription:
        'From digital campaigns and integrated campaigns, to outdoor and print campaigns – our creative strategy is rooted in a simple yet powerful human insight unique to your brand and product or service. Send us a campaign brief today.',
      bgColor: '#ffffff',
      textColor: '#13c33f',
      href: '/advertising-agency',
    },
    {
      id: 4,
      serviceTitle: 'BOOK A CREW',
      serviceDescription:
        'Get on-demand professional video crews anywhere in the world. Be it a one-camera shoot or a multi-camera multi-location production–we curate and manage the production, and quality-check the footage for you. Hire a professional video crew today!',
      bgColor: '#ffffff',
      textColor: '#13c33f',
      href: '/video-production-near-me',
    },
  ]